### ISSUE TITLE
No value for moon orbit in relation to it's planet?

### ISSUE THREAD

**Issue by sirus20x6** [LeonidGrr/accrete#18]
since a and b seem to be related to the primary star there doesn't seem to be anything in the json about the distance the moon should be from it's parent planet.

I would like to add moons to my visualization 
https://media.discordapp.net/attachments/760742011283308544/1040352399606431784/image.png

**Comment by sirus20x6** [comment]
oh i think I see. a is to parent planet and b is to star. I'm not sure if those variables should be reused like that

**Comment by LeonidGrr** [comment]
@sirus20x6 Hi! a(semi-major) and b(semi-minor) axis describes elliptical orbit and both should be always relative to parent body(used as barycenter).
If you got some moon with a related to parent planet and b related to primary star it is probably a bug.
I will look into it. Could you please provide json output and seed for random generator (if used).

**Comment by sirus20x6** [comment]
I think I see the issue I am using seed 61585120 and clicked system. then take a look at the first moon.
"a": 0.00007279845380371499
"b": 0.4739992909155078
I'm using your web examples. I see you recently fixed a bug on the rust side, but the examples directory straight from github still has that bug. I don't know rust so I'm not sure how to compile the rust code to regenerate that.

**Comment by LeonidGrr** [comment]
@sirus20x6 Ok, probably I should publish new version for npm package. I will do this in a 1-2 days and then ping you in comments.
Great thank you for pointing to this bug!

**Comment by LeonidGrr** [comment]
@sirus20x6 Please pull last changes from repo and check example once more - it should be fixed. Please let me know if you have any problems with it Also published version 0.2.3 of npm package with same fix.

**Comment by sirus20x6** [comment]
I will give it a try. 
Which version of accrete did you base your rust version on? i had added json exporting to one version so I could use it to make star systems for a video game when I found I had been using a much older version than what was available. I eventually forked https://github.com/omega13a/stargen and started updating that to be c++ but it's going to be a lot of work to get rid of all the globals and preprocessor macros.

**Comment by LeonidGrr** [comment]
@sirus20x6 Actually I didn't used one particular version of accrete. My code is more like a combination of multiple accrete incarnations - mostly Stargen and some js-variants of accrete (there's a links in readme.md).

If you just want to get json and don't want to rewrite your own accrete just let me know and I will compile executable with json output for you.

**Comment by sirus20x6** [comment]
yeah I'm in the same boat. I already added json support to one version and then I found https://github.com/omega13a/stargen had a more fleshed out feature rich version than what I was based off of. So i'm starting again https://github.com/sirus20x6/stargen
So far I've been just converting the c version to c++ and adding doxygen comments. i fixed a few possible null reference bugs, commented out some assignments that were never read, and I'm starting to make it more object oriented. I'm going to add JSON support soon not just for exports, but this version supports solar system catalogs, but they are hard coded as arrays. I'm going to dump them as JSON and then have them be bundled as such with the code rather than be inside it. this would let people add in their own systems with that catalog feature.

**Comment by LeonidGrr** [comment]
Nice idea about catalogs! I will definitely check it when you finish!
It is not documented but in my rust version of accrete I've added some event sourcing, so one can reproduce system generation step by step. But rendering dynamics dest betls and all planetary interactions and motions in line with events log is quite comlicated task. So I keep it for a better times.

**Comment by sirus20x6** [comment]
I'm also concurrently making a video game in godot using the outputted JSON data https://youtu.be/XFIZItbkZRY pretty rough right now. I'm just doing 2d to verify everything and then will switch it to 3d.

**Comment by LeonidGrr** [comment]
@sirus20x6 Thanks for the link! Will follow your progress there.

**Comment by LeonidGrr** [comment]
@sirus20x6 For you render, for planetary orbits i recommend to account for eccentricity and semi minor axis (if you didn't already). Math for it is not complex at all and will make them look elliptical and probably more realistic.

**Comment by sirus20x6** [comment]
I haven't accounted for them yet, but I wanted something simple to prove out a few things before switching to 3d. when I remake it in 3d I'll take that into account. I'm not even really sure how to get realistic periodicity. I was just spawning moons at fractions of a circle around the planet based on how many there were.
