### ISSUE TITLE
use of undeclared crate or module `accrete`

### ISSUE THREAD

**Issue by Wicpar** [LeonidGrr/accrete#5]
Hi, I'm attemting to use your crate in a rust project (not wasm) and i' m getting this error.

```
error[E0433]: failed to resolve: use of undeclared crate or module `accrete`
 --> src\main.rs:1:5
  |
1 | use accrete::accrete::Accrete;
  |     ^^^^^^^ use of undeclared crate or module `accrete`
```

Is there a way you can fix that and publish a new release on crates.io so it can be used out of the box ?
In the mean time I have copied over the sources and done the appropriate modifications to get it to work.

**Comment by Wicpar** [comment]
Hi @LeonidGrr, 
Thanks for the quick fix !

The specific error I posted seems to be resolved.
Could you also make the various structs public from outside the crate ? I cannot import any besides Accrete, and thus cannot compile my code in its entirety.

I've been trying to render the generated systems for a pet game project, however there is lacking documentation, and probably a few features that would be nice as well. 
I'll be glad to contribute a bit.
Here's a screenshot:
![image](https://user-images.githubusercontent.com/5405183/137769304-cd90fb30-628a-411b-ac6f-773de65ca030.png)

Anyway, good job for the port, seems to work well and fast enough.

**Comment by LeonidGrr** [comment]
@Wicpar Thank you. You're welcome!
